[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-run --chip nRF9160_xxAA"

rustflags = [
    "-C", "link-arg=-Tlink.x",
    "-C", "link-arg=--nmagic"
]

[build]
target = "thumbv8m.main-none-eabihf"